# Generated by Django 4.1.7 on 2023-05-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_watchlist_ownerwatchlist_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
