# Generated by Django 4.1.7 on 2023-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_listname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bids',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidsa',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
