# Generated by Django 4.1.7 on 2023-05-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bids_bids_bids_bidsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='ListID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
