# Generated by Django 4.1.7 on 2023-05-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bids_listid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='ListID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bd', to='auctions.listing'),
        ),
    ]
