# Generated by Django 4.1.7 on 2023-05-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bids_listid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='ListID',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
