# Generated by Django 4.1.7 on 2023-05-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidsa',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='list_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_list_id', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
